### PR TITLE
[JENKINS-63223] - Stop passing jenkins.exe.config is no longer available in the Core + Update Minimum Jenkins Core requirement to 2.249.1 + Use Bills of materials to specify core and plugin dependencies

### PR DESCRIPTION
**Pull request by akrist**
jenkins.exe.config was removed from Jenkins, copy attempt fails with NullPointerException

### CODE REVIEW

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
Thanks for submitting a patch! I suggest to also bump the Jenkins core version requirement to 2.249.1. It will allow to prevent misbehavior on older LTS versions

**Comment by oleg-nenashev** [comment]
```
[2020-09-30T10:59:50.866Z] [WARNING] Rule 4: org.apache.maven.plugins.enforcer.RequireUpperBoundDeps failed with message:

[2020-09-30T10:59:50.866Z] Failed while enforcing RequireUpperBoundDeps. The error(s) are [

[2020-09-30T10:59:50.866Z] Require upper bound dependencies error for org.slf4j:jcl-over-slf4j:1.7.25 paths to dependency are:

[2020-09-30T10:59:50.866Z] +-org.jenkins-ci.plugins:windows-slaves:1.7-SNAPSHOT

[2020-09-30T10:59:50.866Z]   +-org.slf4j:jcl-over-slf4j:1.7.25

[2020-09-30T10:59:50.866Z] and

[2020-09-30T10:59:50.866Z] +-org.jenkins-ci.plugins:windows-slaves:1.7-SNAPSHOT

[2020-09-30T10:59:50.866Z]   +-org.jenkins-ci.main:jenkins-core:2.249.1

[2020-09-30T10:59:50.866Z]     +-org.slf4j:jcl-over-slf4j:1.7.26

[2020-09-30T10:59:50.866Z] , 

[2020-09-30T10:59:50.866Z] Require upper bound dependencies error for org.slf4j:log4j-over-slf4j:1.7.25 paths to dependency are:

[2020-09-30T10:59:50.866Z] +-org.jenkins-ci.plugins:windows-slaves:1.7-SNAPSHOT

[2020-09-30T10:59:50.866Z]   +-org.slf4j:log4j-over-slf4j:1.7.25

[2020-09-30T10:59:50.866Z] and

[2020-09-30T10:59:50.866Z] +-org.jenkins-ci.plugins:windows-slaves:1.7-SNAPSHOT

[2020-09-30T10:59:50.866Z]   +-org.jenkins-ci.main:jenkins-core:2.249.1

[2020-09-30T10:59:50.866Z]     +-org.slf4j:log4j-over-slf4j:1.7.26

[2020-09-30T10:59:50.866Z] , 

[2020-09-30T10:59:50.866Z] Require upper bound dependencies error for org.slf4j:slf4j-jdk14:1.7.25 paths to dependency are:

[2020-09-30T10:59:50.866Z] +-org.jenkins-ci.plugins:windows-slaves:1.7-SNAPSHOT

[2020-09-30T10:59:50.866Z]   +-org.slf4j:slf4j-jdk14:1.7.25

[2020-09-30T10:59:50.866Z] and

[2020-09-30T10:59:50.866Z] +-org.jenkins-ci.plugins:windows-slaves:1.7-SNAPSHOT

[2020-09-30T10:59:50.866Z]   +-org.jenkins-ci.main:jenkins-war:2.249.1

[2020-09-30T10:59:50.866Z]     +-org.slf4j:slf4j-jdk14:1.7.26
```

needs a more sophisticated patch. I would recommend using updating Parent POM to the recent version and using the default Bill of Materials provided by it. @akrist let me know if you want me to do that and to save your time

**Comment by akrist** [comment]
@oleg-nenashev Thanks, that would be kind of you could do that.

**Comment by oleg-nenashev** [comment]
There is a strange error happening during the build with JDK11:

```
Error
hudson.init.InitMilestone.SYSTEM_CONFIG_LOADED
Stacktrace
java.lang.EnumConstantNotPresentException: hudson.init.InitMilestone.SYSTEM_CONFIG_LOADED
	at java.base/sun.reflect.annotation.EnumConstantNotPresentExceptionProxy.generateException(EnumConstantNotPresentExceptionProxy.java:46)
	at java.base/sun.reflect.annotation.AnnotationInvocationHandler.invoke(AnnotationInvocationHandler.java:86)
	at com.sun.proxy.$Proxy44.after(Unknown Source)
	at hudson.init.InitializerFinder.afterOf(InitializerFinder.java:60)
	at hudson.init.InitializerFinder.afterOf(InitializerFinder.java:33)
	at hudson.init.TaskMethodFinder$TaskImpl.<init>(TaskMethodFinder.java:140)
	at hudson.init.TaskMethodFinder$TaskImpl.<init>(TaskMethodFinder.java:131)
	at hudson.init.TaskMethodFinder.discoverTasks(TaskMethodFinder.java:62)
	at hudson.init.InitializerFinder.discoverTasks(InitializerFinder.java:33)
	at hudson.init.TaskMethodFinder.discoverTasks(TaskMethodFinder.java:32)
	at org.jvnet.hudson.reactor.TaskBuilder$2.discoverTasks(TaskBuilder.java:61)
	at org.jvnet.hudson.reactor.Reactor.<init>(Reactor.java:151)
	at org.jvnet.hudson.reactor.Reactor.<init>(Reactor.java:156)
	at jenkins.model.Jenkins$5.<init>(Jenkins.java:1079)
	at jenkins.model.Jenkins.executeReactor(Jenkins.java:1079)
	at jenkins.model.Jenkins.<init>(Jenkins.java:932)
	at hudson.model.Hudson.<init>(Hudson.java:85)
	at org.jvnet.hudson.test.JenkinsRule.newHudson(JenkinsRule.java:686)
	at org.jvnet.hudson.test.JenkinsRule.before(JenkinsRule.java:402)
	at org.jvnet.hudson.test.JenkinsRule$1.evaluate(JenkinsRule.java:593)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Looks like it used old Jenkins core during the JDK 11 build, will try to reproduce locally

**Review by oleg-nenashev — APPROVED** [review]
Ready to go once the build is green. I will finish it and release after it

**Comment by oleg-nenashev** [comment]
Thanks a lot @akrist ! It was released in 1.7: https://github.com/jenkinsci/windows-slaves-plugin/releases/tag/windows-slaves-1.7

**Pull request merged**
