### PR TITLE
Small RFE for dependency

### PR DESCRIPTION
**Pull request by slide**
- Make jCIFS dependency local instead of relying on a dependency in core
- Add Jenkinsfile for building

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
@slide I'd guess it's a follow-up to https://github.com/jenkinsci/jenkins/pull/3318 . Could you please clarify what you're trying to achieve in this PR? Even if we have a library locally, there is no guarantee that classloading will actually happen from it

**Comment by slide** [comment]
@oleg-nenashev, yes, it's a follow up to that PR. I am trying to localize the dependency and I understand that without a change in core, the version from core will be loaded for now. This is just to allow removing the dependency from core at some future date.

**Comment by oleg-nenashev** [comment]
Even if you define a dependency here, you cannot guarantee that it will be actually loaded from here. Depends on the class loading order in this and other plugins. Once the core dependency changes, it may lead to upper bound dependency checks here.

As we discussed in https://github.com/jenkinsci/jenkins/pull/3318 , a correct way would be to detach the jcifs API Plugin from the core and then add a dependency on it in this plugin.

**Comment by slide** [comment]
The plan would be to remove the core dependency, there should be no reason to keep it.

**Comment by oleg-nenashev** [comment]
@escoem also pointed me to https://issues.jenkins-ci.org/browse/JENKINS-46255, which is kinda related. Maybe the plugin should just move out to another lib

**Comment by slide** [comment]
I am using jcifs-ng (https://github.com/AgNO3/jcifs-ng) now in po-cifs which has support for SMBv2

**Pull request closed without merging**
