### PR TITLE
[JENKINS-25785] Implement credentials support

### PR DESCRIPTION
**Pull request by Vlatombe**
Todo:
- [x] Update parent pom to a jenkins release with https://github.com/jenkinsci/jenkins/pull/1735 integrated

### CODE REVIEW

**Comment by Vlatombe** [comment]
I'm still forced to keep the exclusion on SECURITY-144-compat : it has been fixed on maven-plugin master https://github.com/jenkinsci/maven-plugin/commit/4609b712d86d90702dfbbb92c912cb9e6bc2ebb5) but it would need a new release + a new release of test-harness using this new release.

**Comment by oleg-nenashev** [comment]
@Vlatombe is it still alive?

**Review by oleg-nenashev — CHANGES_REQUESTED** [review]
It is @reviewbybees now. If @Vlatombe is still interested in getting it delivered, it needs some polishing. But the change is still useful in general

**Comment by oleg-nenashev** [comment]
🐛 , I'd guess

**Comment by oleg-nenashev** [comment]
Closing due to inactivity.
@Vlatombe please feel free to recover if you are still interested

**Pull request closed without merging**
